/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AirTicketBooking;

import static AirTicketBooking.login.username;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Ayushi Saxena
 */
public class Cancellation extends javax.swing.JFrame {
static String username;
static String password;
static String flightno;
static String date;
static int  f=0,g=0;
    /**
     * Creates new form Cancellation
     */
    public Cancellation() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf4 = new datechooser.beans.DateChooserCombo();
        tf3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tf2 = new javax.swing.JPasswordField();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("BOOKING CANCELLATION");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 60, 533, 41);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("ENTER FLIGHT NO :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 290, 215, 34);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(356, 279, 0, 0);

        tf4.setCalendarPreferredSize(new java.awt.Dimension(350, 250));
        tf4.setNothingAllowed(false);
        tf4.setFieldFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", java.awt.Font.PLAIN, 30));
        getContentPane().add(tf4);
        tf4.setBounds(710, 350, 229, 35);

        tf3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        tf3.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(tf3);
        tf3.setBounds(710, 280, 229, 40);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setText("DATE OF FLIGHT :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 360, 215, 34);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("ENTER USERNAME :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(410, 150, 222, 34);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("ENTER PASSWORD :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(410, 220, 222, 34);

        tf1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        tf1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(tf1);
        tf1.setBounds(710, 150, 229, 40);

        jButton1.setBackground(new java.awt.Color(0, 0, 153));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 255, 255));
        jButton1.setText("CONFIRM CANCELLATION ?");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(480, 520, 382, 44);

        tf2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        getContentPane().add(tf2);
        tf2.setBounds(710, 218, 230, 40);

        cb1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 40)); // NOI18N
        cb1.setForeground(new java.awt.Color(0, 0, 204));
        cb1.setText("Business");
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });
        getContentPane().add(cb1);
        cb1.setBounds(490, 440, 160, 52);

        cb2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 40)); // NOI18N
        cb2.setForeground(new java.awt.Color(0, 0, 204));
        cb2.setText("Economy");
        cb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb2ActionPerformed(evt);
            }
        });
        getContentPane().add(cb2);
        cb2.setBounds(740, 440, 160, 52);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketBooking/clouds3.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, -10, 1370, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        username = tf1.getText();
        password = tf2.getText();
        flightno = tf3.getText();
        date = tf4.getText();
       
        //
         Connection c = null;

     
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","ays","mydbms123");
            PreparedStatement  pst = c.prepareStatement("select * from login where username = ? and password = ?");
            pst.setString(1, username); // name is the name of variable in code
            pst.setString(2, password);   // id is name of variable taken in code
            
         
             ResultSet a = pst.executeQuery();
             
             
              while(a.next()){
                          
               
                f=1;
              }
              
              if(username.isEmpty() || username == null){
                  
                    JOptionPane.showMessageDialog(this,"Username Field is Empty");
         }
             else if(password.isEmpty() || password == null){
             JOptionPane.showMessageDialog(this, "Please Enter Password");
                }
            
            else if(f ==0){
                   
                       JOptionPane.showMessageDialog(this,"Incorrect Username Or Password");
                       this.setVisible(true);
                       
               }
              // entry into domestic or international
            else{
              String seattype = "";
             int seats=0;
              if(cb1.isSelected()){
                PreparedStatement  pst1 = c.prepareStatement("select * from userdetails where username = ? and flightno = ? and when = ? and seattype = ?");
                pst1.setString(1, username); // name is the name of variable in code
                
                pst1.setString(2,flightno);
                pst1.setString(3,date);
                pst1.setString(4,cb1.getText());
                ResultSet s = pst1.executeQuery();
                while(s.next()){
                    g=1;
                     seattype = s.getString(4);
                      seats = s.getInt(5);
                     
            PreparedStatement pst2 = c.prepareStatement("update international set business_seats = business_seats + ? where flightno = ? ");
            pst2.setInt(1,seats);
            pst2.setString(2, flightno);
            int e = pst2.executeUpdate();
            
            PreparedStatement pst3 = c.prepareStatement("update domestic set business_seats = business_seats + ? where flightno = ? ");
            pst3.setInt(1,seats);
            pst3.setString(2, flightno);
            int l = pst3.executeUpdate();
                      
                }
              }
              else
              {
                  PreparedStatement  pst1 = c.prepareStatement("select * from userdetails where username = ? and flightno = ? and when = ? and seattype = ?");
                pst1.setString(1, username); // name is the name of variable in code
                
                pst1.setString(2,flightno);
                pst1.setString(3,date);
                pst1.setString(4,cb2.getText());
                ResultSet s = pst1.executeQuery();
                while(s.next()){
                    g=1;
                     seattype = s.getString(4);
                      seats = s.getInt(5);
                       
            
            
            
            if(seattype.equals("Economy")&&cb2.isSelected()){
             
            PreparedStatement pst4 = c.prepareStatement("update international set economy_seats = economy_seats + ? where flightno = ? ");
            pst4.setInt(1,seats);
            pst4.setString(2,flightno);
            int h = pst4.executeUpdate();
                
             PreparedStatement pst5 = c.prepareStatement("update domestic set economy_seats = economy_seats + ? where flightno = ? ");
            pst5.setInt(1,seats);
            pst5.setString(2,flightno);
            int i = pst5.executeUpdate();
             }
              }
                }
                
                  
              
//            if(seattype.equals("Business")&&cb1.isSelected()){
//            
//            PreparedStatement pst2 = c.prepareStatement("update international set business_seats = business_seats + ? where flightno = ? ");
//            pst2.setInt(1,seats);
//            pst2.setString(2, flightno);
//            int e = pst2.executeUpdate();
//            
//            PreparedStatement pst3 = c.prepareStatement("update domestic set business_seats = business_seats + ? where flightno = ? ");
//            pst3.setInt(1,seats);
//            pst3.setString(2, flightno);
//            int l = pst3.executeUpdate();
//            
//            
//           
//            
//            }
//            else if(seattype.equals("Economy")&&cb2.isSelected()){
//             
//            PreparedStatement pst4 = c.prepareStatement("update international set economy_seats = economy_seats + ? where flightno = ? ");
//            pst4.setInt(1,seats);
//            pst4.setString(2,flightno);
//            int h = pst4.executeUpdate();
//                
//             PreparedStatement pst5 = c.prepareStatement("update domestic set economy_seats = economy_seats + ? where flightno = ? ");
//            pst5.setInt(1,seats);
//            pst5.setString(2,flightno);
//            int i = pst5.executeUpdate();
//                        
//            
//           
//                }
//                  
                
              if(g==1){
                  JOptionPane.showMessageDialog(this,"CANCELLATION PROCESS SUCCESSFULL");
                  
            PreparedStatement pst2 = c.prepareStatement("delete from userdetails where flightno = ? and username = ? and seattype = ? and when = ?");
            pst2.setString(1,flightno);
            pst2.setString(2,username);
            pst2.setString(3,seattype);
            pst2.setString(4, date);
            int d = pst2.executeUpdate();
            
            thanks t = new thanks();
              t.setVisible(true);
              t.setExtendedState(MAXIMIZED_BOTH);
              this.dispose();
                  
              }
              else
              {
                 JOptionPane.showMessageDialog(this,"NO RECORDS FOUND"); 
              }
              
              
            }
        
        }
        
        
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    private void cb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancellation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tf1;
    private javax.swing.JPasswordField tf2;
    private javax.swing.JTextField tf3;
    private datechooser.beans.DateChooserCombo tf4;
    // End of variables declaration//GEN-END:variables
}
