/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AirTicketBooking;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;


/**
 *
 * @author Ayushi Saxena
 */
public class Domestic extends javax.swing.JFrame {
    public static String fromwhere;
    public static String to;
    static int adults =0;
    static int children=0;
    static String when;
    static int business = 0;
    static int economy  = 0; 
    static int total=0;
    static String time,time1;
    static String date;
    /**
     * Creates new form Domestic
     */
    public Domestic() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        dateChooserCombo2 = new datechooser.beans.DateChooserCombo();
        dateChooserPanel1 = new datechooser.beans.DateChooserPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spin1 = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        spin2 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        cb1 = new javax.swing.JCheckBox();
        cb2 = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        tf3 = new datechooser.beans.DateChooserCombo();
        tf1 = new javax.swing.JComboBox<>();
        tf2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("FROM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 70, 120, 40);

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 50)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("TO");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(380, 130, 110, 55);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 50)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("WHEN");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(380, 210, 120, 55);

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 50)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("PASSENGERS :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(380, 280, 280, 55);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("ADULTS");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 350, 150, 55);

        spin1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 40)); // NOI18N
        getContentPane().add(spin1);
        spin1.setBounds(580, 350, 70, 50);

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 50)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("CHILDREN");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(700, 350, 190, 55);

        spin2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 40)); // NOI18N
        getContentPane().add(spin2);
        spin2.setBounds(900, 350, 70, 50);

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 0));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(610, 610, 130, 50);

        cb1.setBackground(new java.awt.Color(255, 255, 255));
        cb1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 50)); // NOI18N
        cb1.setForeground(new java.awt.Color(255, 255, 0));
        cb1.setText("BUSINESS");
        getContentPane().add(cb1);
        cb1.setBounds(430, 500, 220, 63);

        cb2.setBackground(new java.awt.Color(255, 255, 255));
        cb2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 50)); // NOI18N
        cb2.setForeground(new java.awt.Color(255, 255, 0));
        cb2.setText("ECONOMY");
        getContentPane().add(cb2);
        cb2.setBounds(720, 500, 230, 60);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(1150, 42, 0, 0);

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 45)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("CLASS OF TRAVEL :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(370, 420, 360, 50);

        tf3.setCalendarPreferredSize(new java.awt.Dimension(350, 250));
        tf3.setNothingAllowed(false);
        tf3.setFieldFont(new java.awt.Font("Tw Cen MT Condensed", java.awt.Font.BOLD, 30));
        try {
            tf3.setForbiddenPeriods(new datechooser.model.multiple.PeriodSet(new datechooser.model.multiple.Period(new java.util.GregorianCalendar(2017, 7, 1),
                new java.util.GregorianCalendar(2017, 7, 1))));
    } catch (datechooser.model.exeptions.IncompatibleDataExeption e1) {
        e1.printStackTrace();
    }
    tf3.setMinDate(Calendar.getInstance());
    tf3.setNavigateFont(new java.awt.Font("Serif", java.awt.Font.BOLD, 20));
    getContentPane().add(tf3);
    tf3.setBounds(560, 210, 220, 40);

    tf1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
    tf1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "delhi", "bangalore", "mumbai", "chennai" }));
    tf1.setSelectedItem(null);
    getContentPane().add(tf1);
    tf1.setBounds(560, 70, 220, 40);

    tf2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 30)); // NOI18N
    tf2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mumbai", "delhi", "kolkata", "bangalore" }));
    tf2.setSelectedItem(null);
    getContentPane().add(tf2);
    tf2.setBounds(560, 140, 220, 40);

    jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketBooking/PicsArt_07-10-11.29.25.jpg"))); // NOI18N
    getContentPane().add(jLabel7);
    jLabel7.setBounds(-50, 0, 1530, 1110);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         
        fromwhere = (String)tf1.getSelectedItem();
        
         to = (String)tf2.getSelectedItem();
         
         when = tf3.getText();
         adults = (Integer)spin1.getValue();  
         children = (Integer)spin2.getValue();
         total = adults+children;
         int m=0;

        
        if(fromwhere.isEmpty() && to.isEmpty() || fromwhere == null && to == null){
            JOptionPane.showMessageDialog(this,"CANNOT LEAVE PLACES TAB EMPTY !!");
        }
         if(adults <=0 ){
            JOptionPane.showMessageDialog(this,"CANNOT LEAVE ADULTS TAB EMPTY !!");
        }
         
        
        else if(!cb1.isSelected() && !cb2.isSelected()){
            JOptionPane.showMessageDialog(this,"CANNOT LEAVE CLASS TAB EMPTY");
        }
        
        else
        {
            //System.out.println("1");
        int f = 0;
        
        if(cb1.isSelected()){
            business = 1;
        }
        else{
            economy = 1;
        }
        
        
        try{
            Connection c = null;
            Class.forName("oracle.jdbc.driver.OracleDriver");
            c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","ays","mydbms123");
            //!
            PreparedStatement  pst3 = c.prepareStatement("select * from domestic where source = ? and destination = ?");
            pst3.setString(1,fromwhere);
            pst3.setString(2,to);
            ResultSet n = pst3.executeQuery();
            while(n.next()){
                m=1;
               // System.out.println("2");
                
            }
             if(m==0){
             //System.out.println("3");
             JOptionPane.showMessageDialog(this,"Sorry no flights available !!");
             } 
//             else{
           // System.out.println("4");
//           
//             PreparedStatement  pst2 = c.prepareStatement("select timeofdept from domestic where source = ? and destination = ?");
//            pst2.setString(1,fromwhere);
//            pst2.setString(2,to);
//            ResultSet e = pst2.executeQuery();
//            while(e.next()){
//                
//             time = e.getString(1);
//            }
//                
//                Date myDate = new Date();
//                SimpleDateFormat mdyFormat = new SimpleDateFormat("d/M/yy");
//                String date = mdyFormat.format(myDate);
//                    
//                Calendar cal = Calendar.getInstance();
//                SimpleDateFormat sdf = new SimpleDateFormat(" HH:mm:ss");
//                time1 = sdf.format(cal.getTime()) ;
//
//             System.out.println(time1.compareTo(time)+" //" + date.compareTo(when)+"??"+when+date);
//              
//            
//             if(date.compareTo(when)<=0  && time1.compareTo(time)<=0){
//              // System.out.println("5");
//                 
//                 JOptionPane.showMessageDialog(this,"!! NO FLIGHTS AVAILABLE");
//                 f=0;
//                 Welcome d =new Welcome();
//                 d.setVisible(true);
//                 d.setExtendedState(MAXIMIZED_BOTH);
//                 this.dispose();
//             }
//                       
            //!
             
            
             else{
                 
            PreparedStatement  pst1 = c.prepareStatement("select business_seats,economy_seats from domestic where source = ? and destination = ?");
            pst1.setString(1,Domestic.fromwhere);
            pst1.setString(2,Domestic.to);
            ResultSet b = pst1.executeQuery();   
            while(b.next()){
               
                TicketBook.bseats1 = b.getInt(1);
                 TicketBook.eseats1 = b.getInt(2);
            }
           if(cb1.isSelected()&&TicketBook.bseats1<=0){
               business=0;
               JOptionPane.showMessageDialog(this,"NO SEATS AVAILABLE IN BUSINESS CLASS!! TRY AGAIN ");
               f=0;
              Welcome w = new Welcome();
               w.setVisible(true);
               w.setExtendedState(MAXIMIZED_BOTH);
               this.dispose();
           }
           else if(cb2.isSelected()&&TicketBook.eseats1<=0){
               economy=0;
               f=0;
               JOptionPane.showMessageDialog(this,"NO SEATS AVAILABLE IN ECONOMY CLASS!! TRY AGAIN ");
               Welcome w = new Welcome();
               w.setVisible(true);
               w.setExtendedState(MAXIMIZED_BOTH);
               this.dispose();
           } 
            
            
            else{
           
            PreparedStatement  pst = c.prepareStatement("select * from domestic where source = ? and destination = ? and  ? between when_start and when_last");
            pst.setString(1,fromwhere);
            pst.setString(2,to);
            pst.setString(3,when);
            ResultSet a = pst.executeQuery();
            
          while(a.next()){
             f = 1; 
             
             TableOfDomestic dtb = new TableOfDomestic();
             dtb.setVisible(true);
             dtb.setExtendedState(MAXIMIZED_BOTH);
             this.dispose();
          }
          if(f==0){
              JOptionPane.showMessageDialog(this,"Sorry no flights available");
          }
           
         
        
          
             }
             }
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed
           
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Domestic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Domestic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Domestic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Domestic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
               new Domestic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cb1;
    private javax.swing.JCheckBox cb2;
    private datechooser.beans.DateChooserCombo dateChooserCombo2;
    private datechooser.beans.DateChooserPanel dateChooserPanel1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSpinner spin1;
    private javax.swing.JSpinner spin2;
    private javax.swing.JComboBox<String> tf1;
    private javax.swing.JComboBox<String> tf2;
    private datechooser.beans.DateChooserCombo tf3;
    // End of variables declaration//GEN-END:variables
}
