/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AirTicketBooking;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ayushi Saxena
 */
public class TableOfInterntl extends javax.swing.JFrame {
    static int adults_fare=0;
    static int children_fare=0;
    static String flightno;
    static String airlines;
    static String time;
    /**
     * Creates new form TableOfInterntl
     */
    public TableOfInterntl() {
        initComponents();
        Connection c = null;
        try{
            Class.forName("oracle.jdbc.driver.OracleDriver");
            c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","ays","mydbms123");
            PreparedStatement  pst = c.prepareStatement("select flightno,airlines,airplanetype,source,destination,timeofdept,timeofarr from international where source = ? and destination = ?");
            pst.setString(1,International.fromwhere);
            pst.setString(2,International.to);
            ResultSet a = pst.executeQuery();
            itable.setModel(DbUtils.resultSetToTableModel(a));
            
            PreparedStatement  pst1 = c.prepareStatement("select flightno,airlines,airplanetype,source,destination,timeofdept,timeofarr from international where source = ? and destination = ?");
            pst1.setString(1,International.fromwhere);
            pst1.setString(2,International.to);
            ResultSet b = pst.executeQuery();
            
            while(b.next()){
                flightno = b.getString(1);
                airlines = b.getString(2);
                time = b.getString(6);
            }
          if(International.business ==1){
            
            PreparedStatement  pst2 = c.prepareStatement("select flightno,business_adults,business_children from internationalfares where flightno = ? ");
            pst2.setString(1,flightno);
            ResultSet d = pst2.executeQuery();
              
            itable2.setModel(DbUtils.resultSetToTableModel(d));
            
            PreparedStatement  pst3 = c.prepareStatement("select flightno,business_adults,business_children from internationalfares where flightno = ?");
            pst3.setString(1,flightno);
            ResultSet e = pst3.executeQuery();
              while(e.next()){
                //flightno = e.getString(1);
                 adults_fare = e.getInt(2);
                 children_fare = e.getInt(3);
                
            }
          
          
          
          
          }
          // for economy class of international
            else{
                PreparedStatement  pst2 = c.prepareStatement("select flightno,economy_adults,economy_children from internationalfares  where flightno = ? ");
            pst2.setString(1,flightno);
            ResultSet d = pst2.executeQuery();
             
            itable2.setModel(DbUtils.resultSetToTableModel(d));
            
            PreparedStatement  pst3 = c.prepareStatement("select flightno,economy_adults,economy_children from internationalfares where flightno= ? ");
            pst3.setString(1,International.fromwhere);
            pst3.setString(2,International.to);
            ResultSet e = pst3.executeQuery();
             while(e.next()){
                
                 adults_fare = e.getInt(2);
                 children_fare = e.getInt(3);
             }    
          }  
            c.close();
        }
        //end of try
        catch(Exception e){
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itable = new javax.swing.JTable();
        B1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        itable2 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("AVAILABLE FLIGHTS :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 80, 630, 77);

        itable.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 25)); // NOI18N
        itable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        itable.setGridColor(new java.awt.Color(255, 153, 51));
        itable.setRowHeight(30);
        jScrollPane1.setViewportView(itable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 180, 1220, 80);

        B1.setBackground(new java.awt.Color(255, 51, 0));
        B1.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 20)); // NOI18N
        B1.setForeground(new java.awt.Color(255, 204, 0));
        B1.setText("PROCEED TO CONFIRM");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        getContentPane().add(B1);
        B1.setBounds(480, 550, 310, 34);

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 65)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("FARE DETAILS :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 290, 530, 80);

        itable2.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 25)); // NOI18N
        itable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        itable2.setGridColor(new java.awt.Color(255, 102, 0));
        itable2.setMaximumSize(new java.awt.Dimension(2147483647, 120));
        itable2.setMinimumSize(new java.awt.Dimension(60, 120));
        itable2.setPreferredSize(new java.awt.Dimension(300, 120));
        itable2.setRowHeight(30);
        jScrollPane2.setViewportView(itable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(200, 390, 910, 60);

        jButton2.setBackground(new java.awt.Color(255, 51, 0));
        jButton2.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 20)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 204, 0));
        jButton2.setText("GO BACK TO PREVIOUS PAGE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(450, 610, 380, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AirTicketBooking/PicsArt_07-10-11.29.25.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1360, 1030);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        try{
            Connection c = null;
            Class.forName("oracle.jdbc.driver.OracleDriver");
            c = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:xe","ays","mydbms123");
         //  PreparedStatement  pst = c.prepareStatement("select * from international");
           
          // ResultSet a = pst.executeQuery();
           
            
            PreparedStatement pst1 = c.prepareStatement("insert into userdetails(airlines,flightno,seattype,noofseats,when) values (?,?,?,?,?) ");
           
            pst1.setString(2,flightno);
            pst1.setString(1, airlines);
            if(International.business == 1 ){
            pst1.setString(3,"Business");
            }
            else{
                pst1.setString(3, "Economy");
            }
            pst1.setInt(4,International.adults+International.children);
            pst1.setString(5,International.when);
           
            int i =  pst1.executeUpdate();
           if(i <= 0){
               System.out.println("error");
           }
        
        JOptionPane.showMessageDialog(this,"YOU NEED TO LOGIN FIRST");
        
        login l = new login();
        
        l.setVisible(true);
        l.setExtendedState(MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_B1ActionPerformed
    
    catch (Exception e){
    System.out.println(e);}
}


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here
        International i = new International();
        
        i.setVisible(true);
        i.setExtendedState(MAXIMIZED_BOTH);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    


        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TableOfInterntl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TableOfInterntl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TableOfInterntl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TableOfInterntl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableOfInterntl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JTable itable;
    private javax.swing.JTable itable2;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
